# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = 'Tenctl'
copyright = '2026, Aleksa Savić'
author = 'Aleksa Savić'
release = '1.0.2'
version = '1.0.2'

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.napoleon',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx_copybutton',
    'sphinx_inline_tabs',
    'sphinx_design',
    'sphinxcontrib.mermaid',
]

templates_path = ['_templates']
exclude_patterns = []

# The master toctree document
master_doc = 'index'

# The language for content autogenerated by Sphinx
language = 'en'

# Internationalization
locale_dirs = ['../locale/']
gettext_compact = False  # Separate .po per RST file
gettext_uuid = False
gettext_auto_build = True

# Gettext metadata for .po files
gettext_additional_targets = ['index']
gettext_last_translator = 'Aleksa Savić <savicaleksa.kg@gmail.com>'
gettext_language_team = 'Serbian <savicaleksa.kg@gmail.com>'

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
html_css_files = [
    'custom.css',
]

html_theme_options = {
    'logo_only': False,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'style_nav_header_background': '#2980B9',
    # Toc options
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

html_context = {
    "display_github": True,
    "github_user": "Aeterno8",
    "github_repo": "tenctl",
    "github_version": "master",
    "conf_py_path": "/docs/source/",
}

# Custom sidebar templates
html_sidebars = {
    '**': [
        'globaltoc.html',
        'relations.html',
        'sourcelink.html',
        'searchbox.html',
    ]
}

# -- Options for LaTeX output ------------------------------------------------

latex_engine = 'xelatex'
latex_elements = {
    'papersize': 'a4paper',
    'pointsize': '11pt',
    'preamble': r'''
        \usepackage{fontspec}
        \usepackage{polyglossia}
        \setmainlanguage{english}
        \setotherlanguage{serbian}
        \setmainfont{DejaVu Serif}
        \setsansfont{DejaVu Sans}
        \setmonofont{DejaVu Sans Mono}
    ''',
}

# Language-specific PDF titles
if language == 'sr':
    latex_doc_title = 'Документација Tenctl-а'
else:
    latex_doc_title = 'Tenctl Documentation'

latex_documents = [
    (master_doc, 'ProxmoxMultiTenant.tex',
     latex_doc_title,
     'Aleksa Savić', 'manual'),
]

# -- Options for manual page output ------------------------------------------

man_pages = [
    (master_doc, 'tenctl',
     'Tenctl Documentation',
     [author], 1)
]

# -- Options for Texinfo output ----------------------------------------------

texinfo_documents = [
    (master_doc, 'Tenctl',
     'Tenctl Documentation',
     author, 'Tenctl',
     'A multi-tenant management system for Proxmox VE.',
     'Miscellaneous'),
]

# -- Options for EPUB output -------------------------------------------------

epub_title = project
epub_author = author
epub_publisher = author
epub_copyright = copyright

# -- Extension configuration -------------------------------------------------

# sphinx-copybutton configuration
copybutton_prompt_text = r">>> |\.\.\. |\$ |In \[\d*\]: | {2,5}\.\.\.: | {5,8}: "
copybutton_prompt_is_regexp = True
copybutton_only_copy_prompt_lines = True
copybutton_remove_prompts = True

# Mermaid configuration
mermaid_version = "latest"

# Syntax highlighting
highlight_language = 'bash'
pygments_style = 'sphinx'

# Todo extension
todo_include_todos = True

# Intersphinx mapping
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'bash': ('https://www.gnu.org/software/bash/manual/html_node/', None),
}

# Source code links (for self-hosted Git)
# Note: Update this URL to match your Git instance
html_show_sourcelink = True
html_copy_source = True
